repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: name-tests-test
  
  - repo: https://github.com/adamchainz/django-upgrade
    rev: ""  # replace with latest tag on GitHub
    hooks:
      - id: django-upgrade

  - repo: https://github.com/asottile/pyupgrade
    rev: ""
    hooks:
      - id: pyupgrade
        args: [--py313-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: ""
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
